version: '3.6'
services:
    app_web:
        image: nginx
        volumes:
            - ./environment/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./environment/conf/nginx/admin.conf:/etc/nginx/conf.d/admin.conf
            - .:/var/www/html
        ports:
            - 80:80
            - 81:81
        depends_on:
            - app_php
            - app_db
    app_php:
        build: ./environment/
        restart: always
        volumes:
            - ./environment/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./environment/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        ports:
            - 82:82
            - 83:83
    app_composer:
        image: composer
        volumes:
            - ./common:/app
        command: install
    app_db:
        image: postgres:13.2
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./environment/conf/postgres/:/docker-entrypoint-initdb.d/

    app_memcached:
        image: memcached
        command: memcached -m 1024m
        environment:
          - MEMCACHED_MEMORY_LIMIT=1024
